name: Haskell CI

on:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ["ghc8107", "ghc924"]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io/ https://cache.zw3rk.com/ https://cache.nixos.org/
      - name: Prepare dev shell
        run: nix develop github:input-output-hk/iohk-nix?rev=3d984c904d6d7f3f2f06c9c1ae8b1180c1a68d5d#${{ matrix.ghc }} --no-write-lock-file --command true
      - name: Update Cabal Index
        run: nix develop github:input-output-hk/iohk-nix?rev=3d984c904d6d7f3f2f06c9c1ae8b1180c1a68d5d#${{ matrix.ghc }} --no-write-lock-file --command cabal update
      - name: Build dependencies
        run: nix develop github:input-output-hk/iohk-nix?rev=3d984c904d6d7f3f2f06c9c1ae8b1180c1a68d5d#${{ matrix.ghc }} --no-write-lock-file --command cabal build all --only-dependencies -j 
      - name: Build project
        run: nix develop github:input-output-hk/iohk-nix?rev=3d984c904d6d7f3f2f06c9c1ae8b1180c1a68d5d#${{ matrix.ghc }} --no-write-lock-file --command cabal build all -j 
