name: nix-build
on:
  push:
    branches:
      - zliu41/ci
jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        experimental: [false]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout repositiory code
      uses: actions/checkout@v3
    - name: build
      run: nix build .#x86_64-linux.automation.ciJobs.required --accept-flake-config
